---
global:
  natsaddress: "nats://127.0.0.1:4222"
  subject: "eventhandler"

command:
  cmd: "cat"
  cmd_args:
    - "-"
  stdin_template: "{{ . | printf %v }}"
  filters:
    - type: regexp
      context: payload
      args:
        field: "check_name"
        regexp: "check_.+"
    - type: regexp
      context: envelope
      args:
        field: "sender"
        regexp: "nagios.example.com"
    - type: regexp
      context: envelope
      args:
        field: "recipient"
        regexp: "me.example.com"
    - type: replay
      context: last_received
      args:
        blackout: 5s
