---
global:
  stan_address: "localhost:4222"
  client_id: "host.example.com"
  subject: "eventhandler"

command:
  cmd: "cat"
  cmd_args:
    - "-"
  stdin_template: "{{ . | printf %v }}"
  filters:
    - source_field: "hostname"
      regexp_match: "localhost"
    - source_field: "check_name"
      regexp_match: "check_.+"
