---
sender: "nagios.example.com"
recipient: "me.example.com"

global:
  natsaddress: "nats://127.0.0.1:4222"
  subject: "eventhandler"

command:
  cmd: "/bin/cat"
  cmdargs:
    - "-"
  timeout: "2s"
  stdintemplate: '{{ . | printf "%v" }}'
  filters:
    - type: regexp
      context: payload
      args:
        field: "check_name"
        regexp: "check_.+"
    - type: regexp
      context: envelope
      args:
        field: "sender"
        regexp: "nagios.example.com"
    - type: regexp
      context: envelope
      args:
        field: "recipient"
        regexp: "me.example.com"
  blackout: 5s
  maxdispatches: 3
